-- Run this in Supabase SQL Editor.

create table if not exists public.quote_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text,
  phone text,
  email text,
  vehicle text,
  service text,
  message text,
  status text not null default 'new'
);

alter table public.quote_requests enable row level security;

-- Only logged-in users can read requests.
create policy "Authenticated admins can read quote requests"
on public.quote_requests
for select
to authenticated
using (true);

-- Public visitors can submit requests.
create policy "Public can create quote requests"
on public.quote_requests
for insert
to anon
with check (true);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_name text,
  appointment_time timestamptz,
  service text,
  notes text,
  status text not null default 'scheduled'
);

alter table public.appointments enable row level security;

create policy "Authenticated admins can manage appointments"
on public.appointments
for all
to authenticated
using (true)
with check (true);
